<?php

namespace WebAv\PlanningBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActDateRepository extends EntityRepository
{
}
