<?php

namespace WebAv\PlanningBundle\Entity;

use Doctrine\ORM\EntityRepository;
use \Datetime;
use Symfony\Component\DependencyInjection\ContainerInterface as Container;
/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends EntityRepository
{
	public function getEventByMonth($month,$year,$user)
	{



	
	  $debut=new Datetime($year.'-'.($month+1).'-01');
	  $fin=new Datetime($year.'-'.($month+2).'-01');

	  $qb = $this->createQueryBuilder('Reserv')
	  		->leftJoin('Reserv.actdate', 'ad')
	  		->leftJoin('ad.date','d')
	  		->leftJoin('ad.activite','a')
	  		->leftJoin('Reserv.usr', 'u');

	  $qb->where('u.id = :utilisateur')
	  	 ->setParameter('utilisateur', $user);


	  $qb->andWhere('d.date BETWEEN :debut AND :fin')
      	 ->setParameter('debut', $debut)  // Date entre le 1er janvier de cette annM-CM-)e
      	 ->setParameter('fin', $fin); // Et le 31 dM-CM-)cembre de cette annM-CM-)e

	  // On peut ajouter ce qu'on veut aprM-CM-(s
	  $qb->orderBy('d.date', 'ASC');
	  $tab=$qb->getQuery()->getResult();
	  $mesreserv=array();
	 	foreach ($tab as $key => $value) {
	 	$m=$value->getActDate()->getDate();
		$mesreserv[$m->getDate()->format('Y-m-d')][]=$value;
	 	}


	 return $mesreserv;

	}
}
