webav_planningyear:
    pattern:  /Planning/{year}
    defaults: { _controller: WebAvPlanningBundle:Default:index, year: null }

webav_planning:
    pattern:  /
    defaults: { _controller: WebAvPlanningBundle:Default:accueil }


webav_planningaddres:
    pattern:  /Ajouter/reservation
    defaults: { _controller: WebAvPlanningBundle:Default:addres }


webav_planningaddact:
    pattern:  /Ajouter/activite
    defaults: { _controller: WebAvPlanningBundle:Default:addact }